### ISSUE TITLE
Question about FTOT

### ISSUE THREAD

**Issue by jiezhao1219** [VolpeUSDOT/FTOT-Public#14]
Hi @olivia-gillham-volpe @matthewpearlson 

Thanks for your help in the case study about supply chain resilience assessment. Now we plan to apply the resilience assessment on a more realistic case (i.e. forest residuals-to-jet fuel supply chain) based on FTOT framework. During the optimization of this supply chain system, we want to fix some types of nodes, while only optimize other types of nodes. For example, 50 rmp, 12 proc, and 30 dest are applied as inputs into FTOT simulation, we want the outputs to include all the 12 proc and 30 dest nodes with assuming that the optimization only occurs among rmp. Could you give me some recommendations about how to modify the Python files in order to realize this partly optimization?

Thanks,
Jie Zhao (WSU)

**Comment by matthewpearlson** [comment]
HI Jie. 

If I understand your question correctly, it appears you would like to run the optimization for JUST the RMPs to the Proc. If that is the case, this is a pretty straight forward use case. 

In this scenario I would treat the **Processors as Destinations**. This simplifies the problem to be more like QS1. 

The key changes here are: 
(1) updating the facility_commodity CSV file of the proc to remove any of the OUTPUT commodities. In this case I would create a copy of your proc.csv and rename it to proc_as_dest.csv ("processors as destinations"), and keep the input commodities, and remove any of the output commodities. 
(2) remove the processor references from the scenario.xml. in this case you would want to set the  <Base_Processors_Layer>None</Base_Processors_Layer>, and the   <Processors_Commodity_Data>None</Processors_Commodity_Data>.
(3) update the <Base_Destination_Layer> with the locations of your processors.
(4) update the <Destinations_Commodity_Data> with the location of your proc_as_dest.csv file from #1 above. 

I hope that makes sense. Let me know if it isn't clear. 
(3)

**Comment by jiezhao1219** [comment]
Hi @matthewpearlson 

Thanks for your reply. Sorry for misleading, let me clarify my question. We want to run the optimization from RMPs to Proc, to Dest, but we want to fix some types of facilities and don't consider their facility optimization, with assuming that all the input facilities for this fixed type will be used as final supply chain. Let's use QS6 as an example, there are 636 RMPs, 20 Proc, and 20 Dest nodes as the input facility data into FTOT. After optimization, the outputs include 481 RMPs, 7 Proc, and 13 Dest nodes. Now, we want to make some modification to fix all input processors and destinations, and keep all of them to be utilized after optimization. In this case, our optimal results should include these 20 Proc, and 20 Dest nodes, and xxx RMPs (the amount of RMPs depends on the optimization). 

I really appreciate your help and time. 

Thanks,
Jie Zhao (WSU)

**Comment by matthewpearlson** [comment]
Hi Jie. Thanks for clarifying your question about ensuring facilities are used in the FTOT optimization. In the case of QS6, there are several reasons why the optimizer does not use all of the facilities.

First, not all of the RMPs are connected to the network. These "stranded" facilities can be include by increasing the artificial link distances in the XML, and then rerunning the scenario.  The C (connectivity) step will report the stranded material in the log. 

Second, the reason the processors and destinations are not all utilized has to do with the amount of material available, the processing capacity, and the destination demand. Again, using QS6 as an example....
- The total amount of RMP supply is around 18.7MM tons of commodity "A_supply". However, as noted above, not all of this is able to be used because some supply is stranded. Look for the "net supply" table in the C step log or scenario report. 
- The processors have a total capacity of 58.8MM tons of "A_supply", but obviously not all of that capacity is needed because there is only 18.7MM tons of supply. So, I would expect to see something like 7 processors used (calculation: 18.7/58.8 ~= 30% .... 0.3 * 20 proc = 7 processors needed to process all of the supply. )
- The destinations call for 33MM tons of commodity "B_processed". According to the processing ratio defined in the proc.csv file, there is a factor of 1.8 output/input. In otherwords, to produce 33MM tons of product, 33MM/1.8 = 18.3MM tons of input is needed.  Since, there isn't that much supply available, some of the less optimal facilities will be dropped from the final results.

If you'd like to all the facilities to be used, my suggestion would be to either (a) increase the amount of supply available in the scenario, (b) increase the unmet demand penalty in the XML, and (c) reducing the destination demand. 

I hope this explanation is clear. Please let me know if you have more questions.

Thanks! Matthew
